repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: requirements-txt-fixer
        args: ["--fix=lf"]
      - id: check-added-large-files
        args: ["--maxkb=500"]

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-broken-line,
          flake8-markdown,
          flake8-use-fstring,
        ]
        args:
          - --exclude=__pycache__,.pyc
          - --max-line-length=79
          - --select=E,F,W,C90
          - --extend-ignore=E203,W503

  - repo: https://github.com/jorisroovers/gitlint # Lints git message
    rev: v0.17.0
    hooks:
      - id: gitlint
        args: ["--ignore=T5,B6,B7", "--msg-filename"]

  - repo: https://github.com/asottile/pyupgrade # Updates python language to latest features
    rev: v2.18.3
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
      - id: mypy
        exclude: ^docs
        args: ["--ignore-missing-imports", "--no-warn-unused-ignores"]

  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
    -   id: docformatter
        args: ["--in-place"]
